apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hosts.flotilla.work
spec:
  group: flotilla.work
  scope: Namespaced
  names:
    plural: hosts
    singular: host
    kind: Host
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.ready
        - name: Heartbeat
          type: date
          jsonPath: .status.heartbeat_at
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
