apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: placementpolicies.flotilla.work
spec:
  group: flotilla.work
  scope: Namespaced
  names:
    plural: placementpolicies
    singular: placementpolicy
    kind: PlacementPolicy
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Pool
          type: string
          jsonPath: .spec.pool
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
