apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskworkspaces.flotilla.work
spec:
  group: flotilla.work
  scope: Namespaced
  names:
    plural: taskworkspaces
    singular: taskworkspace
    kind: TaskWorkspace
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Convoy
          type: string
          jsonPath: .spec.convoy_ref
        - name: Task
          type: string
          jsonPath: .spec.task
        - name: Phase
          type: string
          jsonPath: .status.phase
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
