use std::{path::PathBuf, sync::Arc};

use clap::Parser;
use color_eyre::Result;
use flotilla_core::{
    agents, config::ConfigStore, daemon::DaemonHandle, in_process::InProcessDaemon, path_context::DaemonHostPath, path_policy::PathPolicy,
};
use flotilla_protocol::{output::OutputFormat, AgentHookEvent, AttachableId, Command, CommandAction, HostName, RepoSelector};
use flotilla_tui::{app, event_log, theme};
use tracing::info;

/// Flotilla: TUI dashboard for managing development workspaces
#[derive(Parser)]
#[command(version)]
struct Cli {
    /// Git repo roots (repeatable; auto-detected from cwd if omitted)
    #[arg(long)]
    repo_root: Vec<PathBuf>,

    /// Config directory
    #[arg(long)]
    config_dir: Option<PathBuf>,

    /// Socket path (default: ${config_dir}/flotilla.sock)
    #[arg(long)]
    socket: Option<PathBuf>,

    /// Run in embedded mode (no daemon, in-process)
    #[arg(long)]
    embedded: bool,

    /// Theme name (catppuccin-mocha, classic)
    #[arg(long)]
    theme: Option<String>,

    /// Output as JSON instead of human-readable text
    #[arg(long, global = true)]
    json: bool,

    /// Repo context for commands that need it (slug, path, or name)
    #[arg(long)]
    repo: Option<String>,

    #[command(subcommand)]
    command: Option<SubCommand>,
}

#[derive(clap::Subcommand)]
enum SubCommand {
    /// Run the daemon server
    Daemon {
        /// Idle timeout in seconds (0 = no timeout)
        #[arg(long, default_value = "300")]
        timeout: u64,
    },
    /// Print repo list and state
    Status,
    /// Stream daemon events to stdout
    Watch,
    /// Show the daemon's current multi-host routing view
    Topology,
    /// Receive agent hook events (called by agent hook systems)
    Hook {
        /// Agent harness name (e.g. claude-code, codex, gemini)
        harness: String,
        /// Event type (e.g. session-start, stop, notification)
        event_type: String,
    },
    /// Install or uninstall agent hook configuration
    Hooks {
        #[command(subcommand)]
        command: HooksSubCommand,
    },

    // --- Domain nouns (generated by flotilla-commands) ---
    /// Manage repositories
    Repo(flotilla_commands::commands::repo::RepoNoun),
    /// Manage checkouts
    Checkout(flotilla_commands::commands::checkout::CheckoutNoun),
    /// Code review (alias on CrNoun itself, not duplicated here)
    Cr(flotilla_commands::commands::cr::CrNoun),
    /// Issues
    Issue(flotilla_commands::commands::issue::IssueNoun),
    /// Cloud agents
    Agent(flotilla_commands::commands::agent::AgentNoun),
    /// Workspaces
    Workspace(flotilla_commands::commands::workspace::WorkspaceNoun),
    /// Manage and route to hosts
    Host(flotilla_commands::commands::host::HostNounPartial),

    /// Generate completions (hidden, called by shell scripts)
    #[command(hide = true)]
    Complete {
        /// The input line to complete
        line: String,
        /// Cursor position within the line
        #[arg(default_value = "0")]
        cursor_pos: usize,
    },
    /// Output shell completion setup scripts
    Completions {
        /// Shell type
        #[arg(value_enum)]
        shell: CompletionShell,
    },
}

#[derive(Clone, clap::ValueEnum)]
enum CompletionShell {
    Bash,
    Zsh,
    Fish,
}

#[derive(clap::Subcommand)]
enum HooksSubCommand {
    /// Install hooks for an agent harness
    Install {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Install to user settings (~/.claude/settings.json)
        #[arg(long)]
        user: bool,
        /// Install to project settings (.claude/settings.json, committed)
        #[arg(long)]
        project: bool,
        /// Install to local project settings (.claude/settings.local.json, gitignored)
        #[arg(long)]
        local: bool,
        /// Show plugin marketplace install instructions instead
        #[arg(long)]
        plugin: bool,
    },
    /// Remove hooks for an agent harness
    Uninstall {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Remove from user settings
        #[arg(long)]
        user: bool,
        /// Remove from project settings
        #[arg(long)]
        project: bool,
        /// Remove from local project settings
        #[arg(long)]
        local: bool,
    },
}

impl Cli {
    fn config_dir(&self) -> PathBuf {
        self.config_dir.clone().unwrap_or_else(|| PathPolicy::from_process_env().config_dir.into_path_buf())
    }

    fn socket_path(&self) -> PathBuf {
        self.socket.clone().unwrap_or_else(|| self.config_dir().join("flotilla.sock"))
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;
    let mut cli = Cli::parse();
    let format = OutputFormat::from_json_flag(cli.json);
    let command = cli.command.take();

    match command {
        Some(SubCommand::Daemon { timeout }) => run_daemon(&cli, timeout).await,
        Some(SubCommand::Status) => run_status(&cli, format).await,
        Some(SubCommand::Watch) => run_watch(&cli, format).await,
        Some(SubCommand::Topology) => run_topology_command(&cli, format).await,
        Some(SubCommand::Hook { harness, event_type }) => run_hook(&cli, &harness, &event_type).await,
        Some(SubCommand::Hooks { command }) => run_hooks_command(&command).await,

        Some(SubCommand::Repo(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Checkout(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Cr(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Issue(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Agent(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Workspace(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Host(partial)) => {
            use flotilla_commands::Refinable;
            dispatch(partial.refine().and_then(|n| n.resolve()).map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await
        }

        Some(SubCommand::Complete { line, cursor_pos }) => {
            run_complete(&line, cursor_pos);
            Ok(())
        }
        Some(SubCommand::Completions { shell }) => {
            run_completions(shell);
            Ok(())
        }

        None => run_tui(cli).await,
    }
}

async fn run_tui(cli: Cli) -> Result<()> {
    let paths = PathPolicy::from_process_env();
    event_log::init_with_dir(paths.state_dir.as_path());
    let startup = std::time::Instant::now();
    let resolved_config_dir = cli.config_dir();
    let config = Arc::new(ConfigStore::new(DaemonHostPath::new(&resolved_config_dir), paths.state_dir.clone()));

    // Initialize terminal and show splash immediately for fast visual feedback.
    // Mouse capture is enabled AFTER the splash so mouse events don't cut it short.
    let mut terminal = ratatui::init();
    flotilla_tui::terminal::install_panic_hook();
    #[cfg(unix)]
    flotilla_tui::terminal::install_sigterm_handler();

    // Resolve repos before splash (fast — just reads config files).
    let embedded = cli.embedded;
    let repo_roots = if embedded {
        let roots = flotilla_core::config::resolve_repo_roots(&cli.repo_root, &config).await;
        if roots.is_empty() {
            flotilla_tui::terminal::restore_terminal();
            eprintln!("Error: no git repositories found (use --repo-root to specify)");
            std::process::exit(1);
        }
        info!(
            repo_count = roots.len(),
            elapsed = ?startup.elapsed(),
            "config loaded"
        );
        roots
    } else {
        vec![]
    };

    let cli_repo_roots = cli.repo_root.clone();
    let cli_theme = cli.theme.clone();

    // Spawn daemon init on a separate task so it runs concurrently with the splash
    // (show_splash uses blocking crossterm::event::poll calls).
    let daemon_log_path = paths.state_dir.as_path().join("daemon.log");
    let daemon_panic_log_path = resolved_config_dir.join("daemon-panic.log");
    let config_clone = Arc::clone(&config);
    let daemon_task = tokio::spawn(async move {
        let daemon: Result<Arc<dyn DaemonHandle>, String> = if embedded {
            let daemon_config = config_clone.load_daemon_config()?;
            let host_name = daemon_config.host_name.map(HostName::new).unwrap_or_else(HostName::local);
            let discovery = flotilla_core::providers::discovery::DiscoveryRuntime::for_process(daemon_config.follower);
            let repo_root_paths = repo_roots.into_iter().map(|p| p.into_path_buf()).collect();
            let d = InProcessDaemon::new(repo_root_paths, Arc::clone(&config_clone), discovery, host_name).await;

            match flotilla_daemon::server::spawn_embedded_peer_networking(Arc::clone(&d), &config_clone) {
                Ok(_peer_networking) => {
                    // Detached background task; the TUI owns the daemon handle.
                }
                Err(e) => {
                    tracing::warn!(err = %e, "peer networking not started in embedded mode");
                }
            }

            Ok(d as Arc<dyn DaemonHandle>)
        } else {
            let socket_path = cli.socket_path();
            flotilla_tui::socket::connect_or_spawn(&socket_path, &resolved_config_dir, cli.config_dir.as_deref(), cli.socket.as_deref())
                .await
                .map(|d| d as Arc<dyn DaemonHandle>)
        };
        daemon
    });

    flotilla_tui::splash::show_splash(&mut terminal).await?;
    let daemon = match daemon_task.await {
        Ok(Ok(daemon)) => {
            info!(elapsed = ?startup.elapsed(), "daemon ready");
            daemon
        }
        Ok(Err(e)) => {
            flotilla_tui::terminal::restore_terminal();
            eprintln!("Error: {e}");
            eprintln!("  Check daemon log at {}", daemon_log_path.display());
            eprintln!("  Check panic log at {}", daemon_panic_log_path.display());
            std::process::exit(1);
        }
        Err(e) => {
            flotilla_tui::terminal::restore_terminal();
            eprintln!("Error: daemon initialization panicked: {e}");
            std::process::exit(1);
        }
    };

    // Forward --repo-root paths to the daemon (socket mode only;
    // in-process mode already received them via InProcessDaemon::new).
    if !embedded {
        for root in &cli_repo_roots {
            let canonical = std::fs::canonicalize(root).unwrap_or_else(|_| root.clone());
            if let Err(e) = daemon
                .execute(flotilla_protocol::Command {
                    host: None,
                    provisioning_target: None,
                    context_repo: None,
                    action: flotilla_protocol::CommandAction::TrackRepoPath { path: canonical.clone() },
                })
                .await
            {
                info!(repo = %canonical.display(), err = %e, "failed to add repo");
            }
        }
    }

    let theme_name = cli_theme.or_else(|| config.load_config().ui.theme.clone()).unwrap_or_else(|| "catppuccin-mocha".to_string());
    let initial_theme = theme::theme_by_name(&theme_name);
    if !initial_theme.name.eq_ignore_ascii_case(&theme_name) {
        tracing::warn!(requested = %theme_name, using = %initial_theme.name, "unknown theme, falling back");
    }

    let repos_info = daemon.list_repos().await.unwrap_or_default();
    let app = app::App::new(daemon.clone(), repos_info, Arc::clone(&config), initial_theme);

    flotilla_tui::run::run_event_loop(terminal, app).await
}

async fn run_daemon(cli: &Cli, timeout_secs: u64) -> Result<()> {
    let paths = PathPolicy::from_process_env();
    flotilla_daemon::cli::run(&cli.socket_path(), &cli.config_dir(), paths.state_dir.as_path(), timeout_secs)
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))
}

/// Reset SIGPIPE so piped CLI commands (e.g. `watch | head`) exit cleanly.
/// Only called for CLI subcommands — not the TUI (which needs terminal restore on exit)
/// or the daemon (which shouldn't be killed by a broken stdout pipe).
#[cfg(unix)]
fn reset_sigpipe() {
    // SAFETY: libc::signal is safe to call before I/O begins. Tokio does not configure SIGPIPE.
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }
}

#[cfg(not(unix))]
fn reset_sigpipe() {}

async fn run_status(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    flotilla_tui::cli::run_status(&cli.socket_path(), format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

async fn run_watch(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    flotilla_tui::cli::run_watch(&cli.socket_path(), format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

async fn connect_daemon(cli: &Cli) -> Result<Arc<dyn DaemonHandle>> {
    let socket_path = cli.socket_path();
    let config_dir = cli.config_dir();
    let daemon = flotilla_tui::socket::connect_or_spawn(&socket_path, &config_dir, cli.config_dir.as_deref(), cli.socket.as_deref())
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;
    Ok(daemon as Arc<dyn DaemonHandle>)
}

async fn run_control_command(cli: &Cli, command: Command, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    let daemon = connect_daemon(cli).await?;
    flotilla_tui::cli::run_command(&*daemon, command, format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

fn resolve_repo_from_env(cli: &Cli) -> Option<RepoSelector> {
    match (&cli.repo, std::env::var("FLOTILLA_REPO").ok()) {
        (Some(repo), _) => Some(RepoSelector::Query(repo.clone())),
        (None, Some(repo)) if !repo.is_empty() => Some(RepoSelector::Query(repo)),
        _ => None,
    }
}

fn set_context_repo(cmd: &mut Command, cli: &Cli) {
    if cmd.context_repo.is_some() {
        return;
    }
    cmd.context_repo = resolve_repo_from_env(cli);
}

fn inject_repo_context(cmd: &mut Command, cli: &Cli) -> Result<()> {
    let repo_selector = resolve_repo_from_env(cli);

    match &mut cmd.action {
        CommandAction::Checkout { repo, .. } if *repo == RepoSelector::Query(String::new()) => {
            *repo = repo_selector.ok_or_else(|| color_eyre::eyre::eyre!("checkout create requires --repo or FLOTILLA_REPO"))?;
        }
        CommandAction::SearchIssues { repo, .. } if *repo == RepoSelector::Query(String::new()) => {
            *repo = repo_selector.clone().ok_or_else(|| color_eyre::eyre::eyre!("issue search requires --repo or FLOTILLA_REPO"))?;
            cmd.context_repo = repo_selector;
        }
        _ => {
            if cmd.context_repo.is_none() {
                cmd.context_repo = repo_selector;
            }
        }
    }
    Ok(())
}

async fn dispatch(resolved: flotilla_commands::Resolved, cli: &Cli, format: OutputFormat) -> Result<()> {
    use flotilla_commands::{RepoContext, Resolved};
    reset_sigpipe();
    match resolved {
        Resolved::Ready(cmd) => run_control_command(cli, cmd, format).await,
        // HostResolution is not interpreted at the CLI edge — SubjectHost and ProviderHost
        // require item context (TUI-only), and ProvisioningTarget is handled by wrapping the
        // command in `host <name> ...` syntax which sets Command.host during noun resolution.
        // Phase 2 palette and TUI dispatch will use HostResolution via resolve_host().
        Resolved::NeedsContext { mut command, repo, .. } => {
            match repo {
                RepoContext::Required => inject_repo_context(&mut command, cli)?,
                RepoContext::Inferred => set_context_repo(&mut command, cli),
            }
            run_control_command(cli, command, format).await
        }
    }
}

async fn run_topology_command(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    let daemon = connect_daemon(cli).await?;
    flotilla_tui::cli::run_topology(&*daemon, format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

async fn run_hook(cli: &Cli, harness: &str, event_type: &str) -> Result<()> {
    use std::io::Read;

    // 1. Resolve harness parser
    let (harness_enum, parser) = agents::parser_for_harness(harness).map_err(|e| color_eyre::eyre::eyre!("unknown harness: {e}"))?;

    // 2. Read native payload from stdin
    let mut payload = Vec::new();
    std::io::stdin().read_to_end(&mut payload).map_err(|e| color_eyre::eyre::eyre!("failed to read stdin: {e}"))?;

    // 3. Parse the event
    let parsed = parser.parse_event(event_type, &payload).map_err(|e| color_eyre::eyre::eyre!("parse error: {e}"))?;

    // 4. Resolve attachable_id from env, or allocate a fresh one.
    // When the daemon receives the event it handles session_id → attachable_id
    // mapping and persistence.
    let attachable_id = match std::env::var("FLOTILLA_ATTACHABLE_ID") {
        Ok(id) if !id.is_empty() => AttachableId::new(id),
        _ => agents::allocate_attachable_id(),
    };

    // 5. Build the event
    let event = AgentHookEvent {
        attachable_id,
        harness: harness_enum,
        event_type: parsed.event_type,
        session_id: parsed.session_id,
        model: parsed.model,
        cwd: parsed.cwd,
    };

    // 6. Send to daemon via socket. The daemon owns agent state as a single
    // actor — no file-level races between concurrent hook processes.
    // Priority: FLOTILLA_DAEMON_SOCKET env > --socket CLI flag > global default.
    let socket_path = std::env::var("FLOTILLA_DAEMON_SOCKET").map(std::path::PathBuf::from).unwrap_or_else(|_| cli.socket_path());

    send_hook_event(&socket_path, event).await
}

/// One-shot client: connect to daemon, send an AgentHook request, read one response, exit.
async fn send_hook_event(socket_path: &std::path::Path, event: AgentHookEvent) -> Result<()> {
    use flotilla_protocol::{framing, Message, Request, ResponseResult};
    use tokio::{
        io::{AsyncBufReadExt, BufReader},
        net::UnixStream,
    };

    let stream = UnixStream::connect(socket_path)
        .await
        .map_err(|e| color_eyre::eyre::eyre!("failed to connect to daemon at {}: {e}", socket_path.display()))?;

    let (reader, mut writer) = stream.into_split();

    // Send request
    let msg = Message::Request { id: 1, request: Request::AgentHook { event } };
    framing::write_message_line(&mut writer, &msg).await.map_err(|e| color_eyre::eyre::eyre!("write error: {e}"))?;

    // Read response
    let mut buf_reader = BufReader::new(reader);
    let mut line = String::new();
    buf_reader.read_line(&mut line).await.map_err(|e| color_eyre::eyre::eyre!("read error: {e}"))?;

    let response: Message = serde_json::from_str(line.trim()).map_err(|e| color_eyre::eyre::eyre!("parse response: {e}"))?;
    match response {
        Message::Response { response, .. } => match *response {
            ResponseResult::Ok { .. } => Ok(()),
            ResponseResult::Err { message } => Err(color_eyre::eyre::eyre!("daemon error: {message}")),
        },
        other => Err(color_eyre::eyre::eyre!("unexpected response: {other:?}")),
    }
}

async fn run_hooks_command(command: &HooksSubCommand) -> Result<()> {
    match command {
        HooksSubCommand::Install { harness, user, project, local, plugin } => {
            if harness != "claude-code" {
                return Err(color_eyre::eyre::eyre!("unknown harness: {harness}. Supported: claude-code"));
            }

            if *plugin {
                println!("To install flotilla hooks as a Claude Code plugin:");
                println!();
                println!("  1. Add the marketplace:");
                println!("     /plugin marketplace add flotilla-org/marketplace");
                println!();
                println!("  2. Install the plugin:");
                println!("     /plugin install flotilla-hooks@flotilla-marketplace");
                return Ok(());
            }

            let scope = resolve_settings_scope(*user, *project, *local)?;
            let path = scope.path();

            install_claude_code_hooks(&path)?;
            println!("Installed flotilla hooks for claude-code in {}", path.display());
            Ok(())
        }
        HooksSubCommand::Uninstall { harness, user, project, local } => {
            if harness != "claude-code" {
                return Err(color_eyre::eyre::eyre!("unknown harness: {harness}. Supported: claude-code"));
            }

            let scope = resolve_settings_scope(*user, *project, *local)?;
            let path = scope.path();

            uninstall_claude_code_hooks(&path)?;
            println!("Removed flotilla hooks for claude-code from {}", path.display());
            Ok(())
        }
    }
}

fn run_complete(line: &str, cursor_pos: usize) {
    use clap::CommandFactory;
    let mut root = Cli::command();
    root.build();
    let completions = flotilla_commands::complete::complete(&root, line, cursor_pos);
    for item in completions {
        if let Some(desc) = &item.description {
            println!("{}\t{desc}", item.value);
        } else {
            println!("{}", item.value);
        }
    }
}

fn run_completions(shell: CompletionShell) {
    match shell {
        CompletionShell::Bash => {
            print!(
                r#"_flotilla() {{
    local completions
    completions="$(flotilla complete "${{COMP_LINE}}" "${{COMP_POINT}}" 2>/dev/null)"
    COMPREPLY=()
    while IFS=$'\t' read -r val _desc; do
        [ -n "$val" ] && COMPREPLY+=("$val")
    done <<< "$completions"
}}
complete -F _flotilla flotilla
"#
            );
        }
        CompletionShell::Zsh => {
            // Pass the full command line and absolute cursor position.
            // words[*] is the full line split by words; CURSOR is the absolute byte offset.
            print!(
                r#"#compdef flotilla
_flotilla() {{
    local -a completions
    local line="${{words[*]}}"
    while IFS=$'\t' read -r val desc; do
        [ -n "$val" ] && completions+=("$val:$desc")
    done < <(flotilla complete "$line" "${{CURSOR}}" 2>/dev/null)
    _describe 'flotilla' completions
}}
compdef _flotilla flotilla
"#
            );
        }
        CompletionShell::Fish => {
            println!(
                r#"complete -c flotilla -f -a '(flotilla complete (commandline -cp) (commandline -C) 2>/dev/null | string replace \t \t)'"#
            );
        }
    }
}

enum SettingsScope {
    User,
    Project,
    Local,
}

impl SettingsScope {
    fn path(&self) -> PathBuf {
        match self {
            SettingsScope::User => {
                std::env::var("HOME").map(PathBuf::from).unwrap_or_else(|_| PathBuf::from("~")).join(".claude/settings.json")
            }
            SettingsScope::Project => find_repo_root().join(".claude/settings.json"),
            SettingsScope::Local => find_repo_root().join(".claude/settings.local.json"),
        }
    }
}

/// Walk up from cwd to find the git repo root (directory containing .git).
/// Falls back to cwd if no .git found.
fn find_repo_root() -> PathBuf {
    let mut dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    loop {
        if dir.join(".git").exists() {
            return dir;
        }
        if !dir.pop() {
            return std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        }
    }
}

fn resolve_settings_scope(user: bool, project: bool, local: bool) -> Result<SettingsScope> {
    match (user, project, local) {
        (true, false, false) => Ok(SettingsScope::User),
        (false, true, false) => Ok(SettingsScope::Project),
        (false, false, true) => Ok(SettingsScope::Local),
        (false, false, false) => Ok(SettingsScope::User), // default
        _ => Err(color_eyre::eyre::eyre!("specify at most one of --user, --project, --local")),
    }
}

fn claude_code_hook_entries() -> serde_json::Value {
    serde_json::json!({
        "SessionStart": [{"matcher": "", "hooks": [{"type": "command", "command": "flotilla hook claude-code session-start"}]}],
        "SessionEnd": [{"matcher": "", "hooks": [{"type": "command", "command": "flotilla hook claude-code session-end"}]}],
        "UserPromptSubmit": [{"matcher": "", "hooks": [{"type": "command", "command": "flotilla hook claude-code user-prompt-submit"}]}],
        "Stop": [{"matcher": "", "hooks": [{"type": "command", "command": "flotilla hook claude-code stop"}]}],
        "Notification": [{"matcher": "permission_prompt", "hooks": [{"type": "command", "command": "flotilla hook claude-code notification"}]}]
    })
}

fn install_claude_code_hooks(path: &std::path::Path) -> Result<()> {
    let mut settings: serde_json::Value = if path.exists() {
        let content = std::fs::read_to_string(path).map_err(|e| color_eyre::eyre::eyre!("failed to read {}: {e}", path.display()))?;
        serde_json::from_str(&content).map_err(|e| color_eyre::eyre::eyre!("failed to parse {}: {e}", path.display()))?
    } else {
        serde_json::json!({})
    };

    let hooks = settings.as_object_mut().expect("settings is object").entry("hooks").or_insert_with(|| serde_json::json!({}));
    let new_entries = claude_code_hook_entries();
    for (event, matchers) in new_entries.as_object().expect("entries is object") {
        let event_hooks = hooks.as_object_mut().expect("hooks is object").entry(event).or_insert_with(|| serde_json::json!([]));
        let existing_arr = event_hooks.as_array().expect("event hooks is array");
        // Check if flotilla hooks are already present
        let already_installed = existing_arr.iter().any(|m| m.to_string().contains("flotilla hook claude-code"));
        if !already_installed {
            let arr = event_hooks.as_array_mut().expect("array");
            for entry in matchers.as_array().expect("matchers array") {
                arr.push(entry.clone());
            }
        }
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| color_eyre::eyre::eyre!("failed to create directory: {e}"))?;
    }
    let json = serde_json::to_string_pretty(&settings).expect("serialize");
    std::fs::write(path, json).map_err(|e| color_eyre::eyre::eyre!("failed to write {}: {e}", path.display()))?;
    Ok(())
}

fn uninstall_claude_code_hooks(path: &std::path::Path) -> Result<()> {
    if !path.exists() {
        return Ok(());
    }
    let content = std::fs::read_to_string(path).map_err(|e| color_eyre::eyre::eyre!("failed to read {}: {e}", path.display()))?;
    let mut settings: serde_json::Value =
        serde_json::from_str(&content).map_err(|e| color_eyre::eyre::eyre!("failed to parse {}: {e}", path.display()))?;

    if let Some(hooks) = settings.get_mut("hooks").and_then(|h| h.as_object_mut()) {
        for (_event, matchers) in hooks.iter_mut() {
            if let Some(arr) = matchers.as_array_mut() {
                arr.retain(|m| !m.to_string().contains("flotilla hook claude-code"));
            }
        }
        // Remove empty event arrays
        hooks.retain(|_, v| v.as_array().is_none_or(|a| !a.is_empty()));
    }

    let json = serde_json::to_string_pretty(&settings).expect("serialize");
    std::fs::write(path, json).map_err(|e| color_eyre::eyre::eyre!("failed to write {}: {e}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::{Cli, SubCommand};

    #[test]
    fn cli_parses_topology_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "topology"]).expect("topology cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(!cli.json);
    }

    #[test]
    fn cli_parses_topology_with_global_json() {
        let cli = Cli::try_parse_from(["flotilla", "topology", "--json"]).expect("topology json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(cli.json);
    }

    #[test]
    fn cli_parses_repo_noun() {
        let cli = Cli::try_parse_from(["flotilla", "repo", "owner/repo"]).expect("repo cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Repo(_))));
    }

    #[test]
    fn cli_parses_checkout_noun() {
        let cli = Cli::try_parse_from(["flotilla", "checkout", "my-feature", "remove"]).expect("checkout cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Checkout(_))));
    }

    #[test]
    fn cli_parses_cr_noun() {
        let cli = Cli::try_parse_from(["flotilla", "cr", "42", "open"]).expect("cr cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Cr(_))));
    }

    #[test]
    fn cli_parses_pr_alias() {
        let cli = Cli::try_parse_from(["flotilla", "pr", "42", "open"]).expect("pr alias should parse");
        assert!(matches!(cli.command, Some(SubCommand::Cr(_))));
    }

    #[test]
    fn cli_parses_issue_noun() {
        let cli = Cli::try_parse_from(["flotilla", "issue", "1", "open"]).expect("issue cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Issue(_))));
    }

    #[test]
    fn cli_parses_agent_noun() {
        let cli = Cli::try_parse_from(["flotilla", "agent", "claude-1", "teleport"]).expect("agent cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Agent(_))));
    }

    #[test]
    fn cli_parses_workspace_noun() {
        let cli = Cli::try_parse_from(["flotilla", "workspace", "feat-ws", "select"]).expect("workspace cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Workspace(_))));
    }

    #[test]
    fn cli_parses_host_noun() {
        let cli = Cli::try_parse_from(["flotilla", "host", "list"]).expect("host list should parse");
        assert!(matches!(cli.command, Some(SubCommand::Host(_))));
    }

    #[test]
    fn cli_parses_host_status_with_json() {
        let cli = Cli::try_parse_from(["flotilla", "host", "alpha", "status", "--json"]).expect("host status json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Host(_))));
        assert!(cli.json);
    }

    #[test]
    fn cli_global_json_before_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "--json", "topology"]).expect("json before subcommand should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(cli.json);
    }

    #[test]
    fn cli_repo_context_flag() {
        let cli = Cli::try_parse_from(["flotilla", "--repo", "owner/repo", "checkout", "create", "--branch", "feat-x"])
            .expect("repo context should parse");
        assert!(matches!(cli.command, Some(SubCommand::Checkout(_))));
        assert_eq!(cli.repo.as_deref(), Some("owner/repo"));
    }

    #[test]
    fn cli_no_subcommand_is_none() {
        let cli = Cli::try_parse_from(["flotilla"]).expect("bare cli should parse");
        assert!(cli.command.is_none());
    }
}
